apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: plex
spec:
  storageClassName: "local-storage-class"
  volumeName: plex-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
